#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# 
# This script captures LPC bus signals from a CSV file and decodes the frames.
# It is designed to work with a specific format of CSV files generated by a logic analyzer.

"""
This script decodes LPC (Low Pin Count) bus signals from a CSV file and interprets the frames 
based on the LPC protocol. It is designed to work with a specific format of CSV files generated 
by a logic analyzer.

Classes:
    LPCDecode:
        A class to interpret LPC frames captured from a CSV file. It processes the signal data, 
        detects the start of frames, captures nibbles, and interprets the frames according to 
        the LPC protocol.

Methods:
    LPCDecode.__init__(file_path="record.csv"):
        Initializes the LPCDecode instance with the specified CSV file path.

    LPCDecode.run():
        Reads the CSV file, processes the signal data, detects frames, and captures nibbles 
        based on the LPC protocol.

    LPCDecode.interpret_frame(nibbles):
        Interprets a single LPC frame based on the captured nibbles. It validates the frame 
        structure and decodes the command, address, and data fields.

    LPCDecode.interpret_all_frames():
        Iterates through all captured frames, decodes them, and prints the interpreted results.

Usage:
    The script is executed by passing the path to the CSV file as a command-line argument. 
    It processes the file, decodes the LPC frames, and prints the interpreted results.

Example:
    $ python3 lpcdecode.py path/to/signal.csv


# This script decodes LPC bus signals from a CSV file and interprets the frames.
# It is designed to work with a specific format of CSV files generated by a logic analyzer.
# The script reads the CSV file, detects the start of frames, captures nibbles,
# and interprets the frames based on the LPC protocol.
"""
# -*- coding: utf-8 -*-

import os
import csv
import sys
# Removed unused import of Saleae
import subprocess
import sys

class LPCDecode:
    """
    Class to interpret LPC frames captured from a CSV file.
    """
    def __init__(self, file_path="record.csv"):
        self._out_file = file_path
        self.recording = False
        self.last_clk = 0
        self.current_nibbles = []
        self.all_frames = []

    def run(self):
        signal_file = self._out_file

        with open(signal_file, "r") as file:
            reader = csv.reader(file)
            for row in reader:
                timestamp = float(row[0])
                lad0 = int(row[1])
                lad1 = int(row[2])
                lad2 = int(row[3])
                lad3 = int(row[4])
                lframe = int(row[5])
                clk = int(row[6])

                # Detect falling edge on LFRAME#
                if lframe == 0 and not self.recording:
                    if self.current_nibbles:
                        self.all_frames.append(self.current_nibbles)
                    self.current_nibbles = []
                    self.recording = True

                # Capture nibbles on rising edge of CLK
                if self.recording:
                    if self.last_clk == 0 and clk == 1:
                        nibble = (lad3 << 3) | (lad2 << 2) | (lad1 << 1) | lad0
                        self.current_nibbles.append((timestamp, nibble))

                self.last_clk = clk

            # Save last frame if any
            if self.current_nibbles:
                self.all_frames.append(self.current_nibbles)

    def interpret_frame(self, nibbles):
        if len(nibbles) < 3:
            return ["Incomplete frame"]

        output = []

        start_code = nibbles[0][1]
        sync_code = nibbles[1][1]
        command = nibbles[2][1]

        if start_code != 0x0:
            output.append("Error: No Start Frame detected")
        if sync_code != 0xF:
            output.append("Error: No Sync Confirm detected")

        if command == 0x1:
            output.append("Command: I/O Read")
        elif command == 0x2:
            output.append("Command: I/O Write")
        else:
            output.append(f"Unknown Command: 0x{command:X}")

        if len(nibbles) >= 7:
            address = (
                (nibbles[3][1] << 12)
                | (nibbles[4][1] << 8)
                | (nibbles[5][1] << 4)
                | nibbles[6][1]
            )
            output.append(f"Address: 0x{address:04X}")

        if len(nibbles) >= 11:
            data = (
                (nibbles[7][1] << 12)
                | (nibbles[8][1] << 8)
                | (nibbles[9][1] << 4)
                | nibbles[10][1]
            )
            output.append(f"Data: 0x{data:04X}")

        return output

    def interpret_all_frames(self):
        for frame in self.all_frames:
            decoded = self.interpret_frame(frame)
            for line in decoded:
                print(line)
            print("---")


recorder = LPCDecode(sys.argv[1])
recorder.run()
recorder.interpret_all_frames()
